### PR TITLE
More illustrative test code

### PR DESCRIPTION
**Pull request by codemartial**
Shows how to use tbsp as an external import. "sq" renamed to "Sq", partially for stylistic reasons ;-) Clearly shows where "Sq" is being tested by renaming TestBasicTabling to TestSq (the tests for tabling are probably already there inside the testing package). gofmt.

PS: Thanks for writing this illustrative package. It does show what the subtest capability brings to the table. Feel free to reject the PR. I just felt this is less effort at my end than engaging in an email exchange :)

### CODE REVIEW

**Comment by sdboyer** [comment]
ah sorry, i've been on vacation and only just saw this!

no, this is great - it makes it much more illustrative (since that's really mostly the goal). if you could just gofmt the code, then i'll happily merge!

**Comment by sdboyer** [comment]
oh, and would it be too much to ask to update the README, as well? 🎉 🎉

**Comment by codemartial** [comment]
Give me a couple of days (because, weekend) and I shall update the README. I'm sure I ran gofmt but there seems to be some disagreement between leading spaces vs. tabs. Will see what to do about that. 👍

**Comment by sdboyer** [comment]
odd. i've never heard of gofmt outputting spaces?

in any case, no rush, and thanks!

**Comment by codemartial** [comment]
Ah, no it's not gofmt. It's because I pasted the code into github's web UI instead of doing a git push. Will fix that next.

**Comment by codemartial** [comment]
The README turned out to be much less of an effort than I was thinking. Looks like we're all done. The whitespace gotcha turned out to be iterm2's fault.

**Comment by sdboyer** [comment]
thanks!

**Pull request merged**
